// Archivo Auto-generado por Kinger
export const ERROR_TYPES = [
  "OK",
  "FALTA: INICIAL",
  "FALTA: CAJA + FINAL",
  "CARPETA VACÍA",
  "SIN CARPETA",
  "FALTA: CAJA",
  "FALTA: INICIAL + CAJA + FINAL",
  "FALTA: FINAL",
  "FALTA: INICIAL + CAJA",
  "FALTA: INICIAL + FINAL"
];
export const GLOBAL_TOTALS = {
  "FALTA: INICIAL": 195,
  "OK": 45061,
  "FALTA: CAJA + FINAL": 652,
  "CARPETA VACÍA": 420,
  "SIN CARPETA": 518,
  "FALTA: CAJA": 133,
  "FALTA: INICIAL + CAJA + FINAL": 40,
  "FALTA: FINAL": 112,
  "FALTA: INICIAL + CAJA": 30,
  "FALTA: INICIAL + FINAL": 6
};
export const RESUMEN_DATA = [
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "61",
    "_stage": "E1",
    "TOTAL_OMISIONES": 222,
    "OK": 214,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 6,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "10",
    "_stage": "E1",
    "TOTAL_OMISIONES": 21,
    "OK": 21,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AREVIR",
    "ID": "16",
    "_stage": "E1",
    "TOTAL_OMISIONES": 34,
    "OK": 10,
    "FALTA: INICIAL": 4,
    "FALTA: CAJA + FINAL": 19,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLAN",
    "ID": "21",
    "_stage": "E1",
    "TOTAL_OMISIONES": 496,
    "OK": 467,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 28,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPAD",
    "ID": "COPAD",
    "_stage": "E1",
    "TOTAL_OMISIONES": 989,
    "OK": 919,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 28,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 40,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "9",
    "_stage": "E1",
    "TOTAL_OMISIONES": 526,
    "OK": 508,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 12,
    "CARPETA VACÍA": 5,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "108",
    "_stage": "E1",
    "TOTAL_OMISIONES": 226,
    "OK": 198,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 5,
    "CARPETA VACÍA": 23,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "17",
    "_stage": "E1",
    "TOTAL_OMISIONES": 121,
    "OK": 41,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 79,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "59",
    "_stage": "E1",
    "TOTAL_OMISIONES": 66,
    "OK": 34,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 5,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 27,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ESCARPIO",
    "ID": "24",
    "_stage": "E1",
    "TOTAL_OMISIONES": 665,
    "OK": 538,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 116,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 5,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "23",
    "_stage": "E1",
    "TOTAL_OMISIONES": 330,
    "OK": 324,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 4,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "20",
    "_stage": "E1",
    "TOTAL_OMISIONES": 100,
    "OK": 98,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "53",
    "_stage": "E1",
    "TOTAL_OMISIONES": 125,
    "OK": 84,
    "FALTA: INICIAL": 5,
    "FALTA: CAJA + FINAL": 15,
    "CARPETA VACÍA": 15,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 3,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 9,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 9,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "54",
    "_stage": "E1",
    "TOTAL_OMISIONES": 15,
    "OK": 1,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 2,
    "CARPETA VACÍA": 2,
    "SIN CARPETA": 10,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 15,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 6,
    "CARPETA VACÍA": 8,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GABETH",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 330,
    "OK": 292,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 36,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GISOL",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 100,
    "OK": 87,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 12,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 624,
    "OK": 618,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 4,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "58",
    "_stage": "E1",
    "TOTAL_OMISIONES": 136,
    "OK": 135,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "18",
    "_stage": "E1",
    "TOTAL_OMISIONES": 226,
    "OK": 226,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 237,
    "OK": 225,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 10,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "53",
    "_stage": "E1",
    "TOTAL_OMISIONES": 5,
    "OK": 2,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 2,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "66",
    "_stage": "E1",
    "TOTAL_OMISIONES": 93,
    "OK": 36,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 57,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 43,
    "OK": 9,
    "FALTA: INICIAL": 33,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "12",
    "_stage": "E1",
    "TOTAL_OMISIONES": 1279,
    "OK": 1138,
    "FALTA: INICIAL": 40,
    "FALTA: CAJA + FINAL": 49,
    "CARPETA VACÍA": 44,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 3,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "REDNI",
    "ID": "8",
    "_stage": "E1",
    "TOTAL_OMISIONES": 263,
    "OK": 248,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 7,
    "SIN CARPETA": 6,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "7",
    "_stage": "E1",
    "TOTAL_OMISIONES": 1215,
    "OK": 1131,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 74,
    "CARPETA VACÍA": 5,
    "SIN CARPETA": 4,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "57",
    "_stage": "E1",
    "TOTAL_OMISIONES": 300,
    "OK": 296,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 3,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "81",
    "_stage": "E1",
    "TOTAL_OMISIONES": 2091,
    "OK": 1844,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 242,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "54",
    "_stage": "E1",
    "TOTAL_OMISIONES": 459,
    "OK": 447,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 9,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "71",
    "_stage": "E1",
    "TOTAL_OMISIONES": 50,
    "OK": 44,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 4,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 2,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 2,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "65",
    "_stage": "E1",
    "TOTAL_OMISIONES": 51,
    "OK": 51,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "70",
    "_stage": "E1",
    "TOTAL_OMISIONES": 60,
    "OK": 54,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 5,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TAYCAR",
    "ID": "14",
    "_stage": "E1",
    "TOTAL_OMISIONES": 192,
    "OK": 76,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 116,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TIERRAZOL",
    "ID": "25",
    "_stage": "E1",
    "TOTAL_OMISIONES": 171,
    "OK": 164,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 6,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "11",
    "_stage": "E1",
    "TOTAL_OMISIONES": 964,
    "OK": 901,
    "FALTA: INICIAL": 8,
    "FALTA: CAJA + FINAL": 11,
    "CARPETA VACÍA": 11,
    "SIN CARPETA": 8,
    "FALTA: CAJA": 12,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 12,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "74",
    "_stage": "E1",
    "TOTAL_OMISIONES": 275,
    "OK": 103,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 119,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 6,
    "FALTA: CAJA": 11,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 36,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "22",
    "_stage": "E1",
    "TOTAL_OMISIONES": 200,
    "OK": 183,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 15,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 2,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "15",
    "_stage": "E1",
    "TOTAL_OMISIONES": 288,
    "OK": 287,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "60",
    "_stage": "E1",
    "TOTAL_OMISIONES": 205,
    "OK": 185,
    "FALTA: INICIAL": 4,
    "FALTA: CAJA + FINAL": 15,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "7",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1184,
    "OK": 1184,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "REDNI",
    "ID": "8",
    "_stage": "E2",
    "TOTAL_OMISIONES": 563,
    "OK": 563,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "10",
    "_stage": "E2",
    "TOTAL_OMISIONES": 309,
    "OK": 309,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "11",
    "_stage": "E2",
    "TOTAL_OMISIONES": 689,
    "OK": 689,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "12",
    "_stage": "E2",
    "TOTAL_OMISIONES": 327,
    "OK": 327,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TAYCAR",
    "ID": "14",
    "_stage": "E2",
    "TOTAL_OMISIONES": 466,
    "OK": 466,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "15",
    "_stage": "E2",
    "TOTAL_OMISIONES": 284,
    "OK": 284,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AREVIR",
    "ID": "16",
    "_stage": "E2",
    "TOTAL_OMISIONES": 21,
    "OK": 21,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "17",
    "_stage": "E2",
    "TOTAL_OMISIONES": 241,
    "OK": 241,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "18",
    "_stage": "E2",
    "TOTAL_OMISIONES": 114,
    "OK": 114,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "19",
    "_stage": "E2",
    "TOTAL_OMISIONES": 481,
    "OK": 481,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GISOL",
    "ID": "20",
    "_stage": "E2",
    "TOTAL_OMISIONES": 376,
    "OK": 376,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLAN",
    "ID": "21",
    "_stage": "E2",
    "TOTAL_OMISIONES": 955,
    "OK": 955,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "22",
    "_stage": "E2",
    "TOTAL_OMISIONES": 337,
    "OK": 303,
    "FALTA: INICIAL": 17,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 8,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 4,
    "FALTA: INICIAL + CAJA": 3,
    "FALTA: INICIAL + FINAL": 2
  },
  {
    "EMPRESA_RAIZ_MASTER": "GABETH",
    "ID": "23",
    "_stage": "E2",
    "TOTAL_OMISIONES": 471,
    "OK": 465,
    "FALTA: INICIAL": 5,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ESCARPIO",
    "ID": "24",
    "_stage": "E2",
    "TOTAL_OMISIONES": 337,
    "OK": 337,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TIERRAZOL",
    "ID": "25",
    "_stage": "E2",
    "TOTAL_OMISIONES": 149,
    "OK": 126,
    "FALTA: INICIAL": 3,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 16,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PROYEP",
    "ID": "52",
    "_stage": "E2",
    "TOTAL_OMISIONES": 332,
    "OK": 332,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "53",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1184,
    "OK": 1184,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "54",
    "_stage": "E2",
    "TOTAL_OMISIONES": 952,
    "OK": 952,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "55",
    "_stage": "E2",
    "TOTAL_OMISIONES": 231,
    "OK": 231,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "56",
    "_stage": "E2",
    "TOTAL_OMISIONES": 192,
    "OK": 192,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "57",
    "_stage": "E2",
    "TOTAL_OMISIONES": 344,
    "OK": 343,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "58",
    "_stage": "E2",
    "TOTAL_OMISIONES": 535,
    "OK": 534,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "59",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1789,
    "OK": 1789,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "60",
    "_stage": "E2",
    "TOTAL_OMISIONES": 301,
    "OK": 301,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "61",
    "_stage": "E2",
    "TOTAL_OMISIONES": 713,
    "OK": 713,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MCORP",
    "ID": "62",
    "_stage": "E2",
    "TOTAL_OMISIONES": 682,
    "OK": 682,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MCORP",
    "ID": "63",
    "_stage": "E2",
    "TOTAL_OMISIONES": 427,
    "OK": 427,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MCORP",
    "ID": "64",
    "_stage": "E2",
    "TOTAL_OMISIONES": 356,
    "OK": 356,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "65",
    "_stage": "E2",
    "TOTAL_OMISIONES": 202,
    "OK": 202,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "66",
    "_stage": "E2",
    "TOTAL_OMISIONES": 175,
    "OK": 175,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "68",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1530,
    "OK": 1530,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "69",
    "_stage": "E2",
    "TOTAL_OMISIONES": 318,
    "OK": 318,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "70",
    "_stage": "E2",
    "TOTAL_OMISIONES": 778,
    "OK": 778,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "71",
    "_stage": "E2",
    "TOTAL_OMISIONES": 674,
    "OK": 674,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "72",
    "_stage": "E2",
    "TOTAL_OMISIONES": 321,
    "OK": 321,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLAN",
    "ID": "73",
    "_stage": "E2",
    "TOTAL_OMISIONES": 177,
    "OK": 177,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "74",
    "_stage": "E2",
    "TOTAL_OMISIONES": 799,
    "OK": 799,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PROYEP",
    "ID": "75",
    "_stage": "E2",
    "TOTAL_OMISIONES": 187,
    "OK": 187,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TIERRAZOL",
    "ID": "76",
    "_stage": "E2",
    "TOTAL_OMISIONES": 198,
    "OK": 144,
    "FALTA: INICIAL": 8,
    "FALTA: CAJA + FINAL": 4,
    "CARPETA VACÍA": 3,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 21,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 14,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 2
  },
  {
    "EMPRESA_RAIZ_MASTER": "REDNI",
    "ID": "77",
    "_stage": "E2",
    "TOTAL_OMISIONES": 291,
    "OK": 291,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "78",
    "_stage": "E2",
    "TOTAL_OMISIONES": 130,
    "OK": 130,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "79",
    "_stage": "E2",
    "TOTAL_OMISIONES": 267,
    "OK": 224,
    "FALTA: INICIAL": 17,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 20,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 6,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "80",
    "_stage": "E2",
    "TOTAL_OMISIONES": 277,
    "OK": 249,
    "FALTA: INICIAL": 14,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 2,
    "FALTA: CAJA": 5,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 6,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "81",
    "_stage": "E2",
    "TOTAL_OMISIONES": 852,
    "OK": 850,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "9",
    "_stage": "E2",
    "TOTAL_OMISIONES": 477,
    "OK": 476,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "67",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1911,
    "OK": 1911,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "1",
    "_stage": "E3",
    "TOTAL_OMISIONES": 205,
    "OK": 205,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "3",
    "_stage": "E3",
    "TOTAL_OMISIONES": 25,
    "OK": 25,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ICI",
    "ID": "4",
    "_stage": "E3",
    "TOTAL_OMISIONES": 314,
    "OK": 314,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ICI",
    "ID": "5",
    "_stage": "E3",
    "TOTAL_OMISIONES": 309,
    "OK": 309,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DOMAJA",
    "ID": "7",
    "_stage": "E3",
    "TOTAL_OMISIONES": 159,
    "OK": 141,
    "FALTA: INICIAL": 6,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 12,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MAMUTEE",
    "ID": "8",
    "_stage": "E3",
    "TOTAL_OMISIONES": 221,
    "OK": 217,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MAMUTEE",
    "ID": "9",
    "_stage": "E3",
    "TOTAL_OMISIONES": 117,
    "OK": 42,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 75,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CREA",
    "ID": "11",
    "_stage": "E3",
    "TOTAL_OMISIONES": 224,
    "OK": 209,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 3,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 6,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 4,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CARASTOL",
    "ID": "12",
    "_stage": "E3",
    "TOTAL_OMISIONES": 147,
    "OK": 147,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CARASTOL",
    "ID": "13",
    "_stage": "E3",
    "TOTAL_OMISIONES": 144,
    "OK": 144,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CARASTOL",
    "ID": "14",
    "_stage": "E3",
    "TOTAL_OMISIONES": 114,
    "OK": 113,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "HISPANO",
    "ID": "15",
    "_stage": "E3",
    "TOTAL_OMISIONES": 128,
    "OK": 128,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "HISPANO",
    "ID": "16",
    "_stage": "E3",
    "TOTAL_OMISIONES": 75,
    "OK": 70,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 4,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "EDIT",
    "ID": "17",
    "_stage": "E3",
    "TOTAL_OMISIONES": 241,
    "OK": 241,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CREA",
    "ID": "18",
    "_stage": "E3",
    "TOTAL_OMISIONES": 263,
    "OK": 241,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 17,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 4,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CREA",
    "ID": "19",
    "_stage": "E3",
    "TOTAL_OMISIONES": 1,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "HISPANO",
    "ID": "19",
    "_stage": "E3",
    "TOTAL_OMISIONES": 96,
    "OK": 95,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "20",
    "_stage": "E3",
    "TOTAL_OMISIONES": 291,
    "OK": 290,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLÁN",
    "ID": "21",
    "_stage": "E3",
    "TOTAL_OMISIONES": 198,
    "OK": 192,
    "FALTA: INICIAL": 2,
    "FALTA: CAJA + FINAL": 3,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "EDITUM",
    "ID": "22",
    "_stage": "E3",
    "TOTAL_OMISIONES": 280,
    "OK": 280,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ARKA",
    "ID": "23",
    "_stage": "E3",
    "TOTAL_OMISIONES": 646,
    "OK": 626,
    "FALTA: INICIAL": 2,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 14,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 3,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TORRE",
    "ID": "24",
    "_stage": "E3",
    "TOTAL_OMISIONES": 229,
    "OK": 229,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CHRISCO",
    "ID": "25",
    "_stage": "E3",
    "TOTAL_OMISIONES": 346,
    "OK": 346,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TORRE",
    "ID": "26",
    "_stage": "E3",
    "TOTAL_OMISIONES": 204,
    "OK": 202,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MAMUTEE",
    "ID": "27",
    "_stage": "E3",
    "TOTAL_OMISIONES": 215,
    "OK": 210,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 5,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MONROY",
    "ID": "28",
    "_stage": "E3",
    "TOTAL_OMISIONES": 178,
    "OK": 178,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SERVIESTRUCT",
    "ID": "29",
    "_stage": "E3",
    "TOTAL_OMISIONES": 53,
    "OK": 51,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SERVIESTRUCT",
    "ID": "30",
    "_stage": "E3",
    "TOTAL_OMISIONES": 77,
    "OK": 61,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 10,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 4,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "31",
    "_stage": "E3",
    "TOTAL_OMISIONES": 63,
    "OK": 63,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "32",
    "_stage": "E3",
    "TOTAL_OMISIONES": 338,
    "OK": 336,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "33",
    "_stage": "E3",
    "TOTAL_OMISIONES": 424,
    "OK": 410,
    "FALTA: INICIAL": 9,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MONROY",
    "ID": "34",
    "_stage": "E3",
    "TOTAL_OMISIONES": 266,
    "OK": 263,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLÁN",
    "ID": "35",
    "_stage": "E3",
    "TOTAL_OMISIONES": 49,
    "OK": 49,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "KANARE",
    "ID": "36",
    "_stage": "E3",
    "TOTAL_OMISIONES": 66,
    "OK": 66,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "EAPRO",
    "ID": "37",
    "_stage": "E3",
    "TOTAL_OMISIONES": 93,
    "OK": 93,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "KANARE",
    "ID": "38",
    "_stage": "E3",
    "TOTAL_OMISIONES": 62,
    "OK": 62,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "EDIT",
    "ID": "39",
    "_stage": "E3",
    "TOTAL_OMISIONES": 329,
    "OK": 328,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "40",
    "_stage": "E3",
    "TOTAL_OMISIONES": 208,
    "OK": 207,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "EAPRO",
    "ID": "41",
    "_stage": "E3",
    "TOTAL_OMISIONES": 167,
    "OK": 66,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 101,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "42",
    "_stage": "E3",
    "TOTAL_OMISIONES": 113,
    "OK": 111,
    "FALTA: INICIAL": 2,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "43",
    "_stage": "E3",
    "TOTAL_OMISIONES": 179,
    "OK": 179,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TERRA",
    "ID": "44",
    "_stage": "E3",
    "TOTAL_OMISIONES": 62,
    "OK": 62,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TERRA",
    "ID": "45",
    "_stage": "E3",
    "TOTAL_OMISIONES": 115,
    "OK": 115,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "INTEGRA",
    "ID": "46",
    "_stage": "E3",
    "TOTAL_OMISIONES": 226,
    "OK": 217,
    "FALTA: INICIAL": 4,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 3,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "INTEGRA",
    "ID": "47",
    "_stage": "E3",
    "TOTAL_OMISIONES": 108,
    "OK": 108,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "CREA",
    "ID": "48",
    "_stage": "E3",
    "TOTAL_OMISIONES": 74,
    "OK": 68,
    "FALTA: INICIAL": 3,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  }
];
export const FILTERS_MAP = {
  "ALSAFI": [
    "61",
    "10",
    "1",
    "31"
  ],
  "AREVIR": [
    "16"
  ],
  "AZTLAN": [
    "21",
    "73"
  ],
  "COPAD": [
    "COPAD"
  ],
  "COPI": [
    "9",
    "108",
    "67"
  ],
  "DAREGA": [
    "17",
    "59"
  ],
  "ESCARPIO": [
    "24"
  ],
  "FENA": [
    "23",
    "20",
    "53",
    "19",
    "54",
    "68",
    "18",
    "66",
    "69",
    "72",
    "78"
  ],
  "GABETH": [
    "68",
    "23"
  ],
  "GISOL": [
    "68",
    "20"
  ],
  "GZALEZ": [
    "68",
    "58",
    "18",
    "19",
    "53"
  ],
  "JDJ": [
    "66",
    "19",
    "58"
  ],
  "PERBOR": [
    "12",
    "55",
    "56",
    "40",
    "42",
    "43"
  ],
  "REDNI": [
    "8",
    "77"
  ],
  "ROCADURA": [
    "7",
    "57",
    "81",
    "3"
  ],
  "SAQEB": [
    "54",
    "71",
    "68",
    "20"
  ],
  "SHAYE": [
    "65",
    "70",
    "32",
    "33"
  ],
  "TAYCAR": [
    "14"
  ],
  "TIERRAZOL": [
    "25",
    "76"
  ],
  "TOVAR": [
    "11",
    "74"
  ],
  "ULTRAPARK": [
    "22",
    "79",
    "80"
  ],
  "VIGOR": [
    "15",
    "60"
  ],
  "PROYEP": [
    "52",
    "75"
  ],
  "MCORP": [
    "62",
    "63",
    "64"
  ],
  "ICI": [
    "4",
    "5"
  ],
  "DOMAJA": [
    "7"
  ],
  "MAMUTEE": [
    "8",
    "9",
    "27"
  ],
  "CREA": [
    "11",
    "18",
    "19",
    "48"
  ],
  "CARASTOL": [
    "12",
    "13",
    "14"
  ],
  "HISPANO": [
    "15",
    "16",
    "19"
  ],
  "EDIT": [
    "17",
    "39"
  ],
  "AZTLÁN": [
    "21",
    "35"
  ],
  "EDITUM": [
    "22"
  ],
  "ARKA": [
    "23"
  ],
  "TORRE": [
    "24",
    "26"
  ],
  "CHRISCO": [
    "25"
  ],
  "MONROY": [
    "28",
    "34"
  ],
  "SERVIESTRUCT": [
    "29",
    "30"
  ],
  "KANARE": [
    "36",
    "38"
  ],
  "EAPRO": [
    "37",
    "41"
  ],
  "TERRA": [
    "44",
    "45"
  ],
  "INTEGRA": [
    "46",
    "47"
  ]
};
