// Archivo Auto-generado por Kinger
export const ERROR_TYPES = [
  "OK",
  "FALTA: INICIAL",
  "FALTA: CAJA + FINAL",
  "CARPETA VACÍA",
  "SIN CARPETA",
  "FALTA: CAJA",
  "FALTA: INICIAL + CAJA + FINAL",
  "FALTA: FINAL",
  "FALTA: INICIAL + CAJA",
  "FALTA: INICIAL + FINAL"
];
export const GLOBAL_TOTALS = {
  "FALTA: INICIAL": 550,
  "OK": 32513,
  "FALTA: CAJA + FINAL": 978,
  "CARPETA VACÍA": 1049,
  "SIN CARPETA": 2214,
  "FALTA: CAJA": 483,
  "FALTA: INICIAL + CAJA + FINAL": 56,
  "FALTA: FINAL": 333,
  "FALTA: INICIAL + CAJA": 331,
  "FALTA: INICIAL + FINAL": 36
};
export const RESUMEN_DATA = [
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "61",
    "_stage": "E1",
    "TOTAL_OMISIONES": 222,
    "OK": 214,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 6,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "10",
    "_stage": "E1",
    "TOTAL_OMISIONES": 21,
    "OK": 21,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AREVIR",
    "ID": "16",
    "_stage": "E1",
    "TOTAL_OMISIONES": 34,
    "OK": 10,
    "FALTA: INICIAL": 4,
    "FALTA: CAJA + FINAL": 19,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLAN",
    "ID": "21",
    "_stage": "E1",
    "TOTAL_OMISIONES": 496,
    "OK": 467,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 28,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPAD",
    "ID": "COPAD",
    "_stage": "E1",
    "TOTAL_OMISIONES": 989,
    "OK": 919,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 28,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 40,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "9",
    "_stage": "E1",
    "TOTAL_OMISIONES": 526,
    "OK": 508,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 12,
    "CARPETA VACÍA": 5,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "108",
    "_stage": "E1",
    "TOTAL_OMISIONES": 226,
    "OK": 198,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 5,
    "CARPETA VACÍA": 23,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "17",
    "_stage": "E1",
    "TOTAL_OMISIONES": 121,
    "OK": 41,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 79,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "59",
    "_stage": "E1",
    "TOTAL_OMISIONES": 66,
    "OK": 34,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 5,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 27,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ESCARPIO",
    "ID": "24",
    "_stage": "E1",
    "TOTAL_OMISIONES": 665,
    "OK": 538,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 116,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 5,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "23",
    "_stage": "E1",
    "TOTAL_OMISIONES": 330,
    "OK": 324,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 4,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "20",
    "_stage": "E1",
    "TOTAL_OMISIONES": 100,
    "OK": 98,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "53",
    "_stage": "E1",
    "TOTAL_OMISIONES": 125,
    "OK": 84,
    "FALTA: INICIAL": 5,
    "FALTA: CAJA + FINAL": 15,
    "CARPETA VACÍA": 15,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 3,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 9,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 9,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "54",
    "_stage": "E1",
    "TOTAL_OMISIONES": 15,
    "OK": 1,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 2,
    "CARPETA VACÍA": 2,
    "SIN CARPETA": 10,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 15,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 6,
    "CARPETA VACÍA": 8,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GABETH",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 330,
    "OK": 292,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 36,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GISOL",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 100,
    "OK": 87,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 12,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 624,
    "OK": 618,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 4,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "58",
    "_stage": "E1",
    "TOTAL_OMISIONES": 136,
    "OK": 135,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "18",
    "_stage": "E1",
    "TOTAL_OMISIONES": 226,
    "OK": 226,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 237,
    "OK": 225,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 10,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "53",
    "_stage": "E1",
    "TOTAL_OMISIONES": 5,
    "OK": 2,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 2,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "66",
    "_stage": "E1",
    "TOTAL_OMISIONES": 93,
    "OK": 36,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 57,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 43,
    "OK": 9,
    "FALTA: INICIAL": 33,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "12",
    "_stage": "E1",
    "TOTAL_OMISIONES": 1279,
    "OK": 1138,
    "FALTA: INICIAL": 40,
    "FALTA: CAJA + FINAL": 49,
    "CARPETA VACÍA": 44,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 3,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "REDNI",
    "ID": "8",
    "_stage": "E1",
    "TOTAL_OMISIONES": 263,
    "OK": 248,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 7,
    "SIN CARPETA": 6,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "7",
    "_stage": "E1",
    "TOTAL_OMISIONES": 1215,
    "OK": 1131,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 74,
    "CARPETA VACÍA": 5,
    "SIN CARPETA": 4,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "57",
    "_stage": "E1",
    "TOTAL_OMISIONES": 300,
    "OK": 296,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 3,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "81",
    "_stage": "E1",
    "TOTAL_OMISIONES": 2091,
    "OK": 1844,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 242,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "54",
    "_stage": "E1",
    "TOTAL_OMISIONES": 459,
    "OK": 447,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 9,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "71",
    "_stage": "E1",
    "TOTAL_OMISIONES": 50,
    "OK": 44,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 4,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 2,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 2,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "65",
    "_stage": "E1",
    "TOTAL_OMISIONES": 51,
    "OK": 51,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "70",
    "_stage": "E1",
    "TOTAL_OMISIONES": 60,
    "OK": 54,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 5,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TAYCAR",
    "ID": "14",
    "_stage": "E1",
    "TOTAL_OMISIONES": 192,
    "OK": 76,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 116,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TIERRAZOL",
    "ID": "25",
    "_stage": "E1",
    "TOTAL_OMISIONES": 171,
    "OK": 164,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 6,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "11",
    "_stage": "E1",
    "TOTAL_OMISIONES": 964,
    "OK": 906,
    "FALTA: INICIAL": 8,
    "FALTA: CAJA + FINAL": 11,
    "CARPETA VACÍA": 11,
    "SIN CARPETA": 8,
    "FALTA: CAJA": 12,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 7,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "74",
    "_stage": "E1",
    "TOTAL_OMISIONES": 275,
    "OK": 113,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 119,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 6,
    "FALTA: CAJA": 10,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 27,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "22",
    "_stage": "E1",
    "TOTAL_OMISIONES": 200,
    "OK": 183,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 15,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 2,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "15",
    "_stage": "E1",
    "TOTAL_OMISIONES": 288,
    "OK": 287,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "60",
    "_stage": "E1",
    "TOTAL_OMISIONES": 205,
    "OK": 185,
    "FALTA: INICIAL": 4,
    "FALTA: CAJA + FINAL": 15,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "7",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1184,
    "OK": 224,
    "FALTA: INICIAL": 104,
    "FALTA: CAJA + FINAL": 8,
    "CARPETA VACÍA": 12,
    "SIN CARPETA": 693,
    "FALTA: CAJA": 16,
    "FALTA: INICIAL + CAJA + FINAL": 12,
    "FALTA: FINAL": 8,
    "FALTA: INICIAL + CAJA": 100,
    "FALTA: INICIAL + FINAL": 7
  },
  {
    "EMPRESA_RAIZ_MASTER": "REDNI",
    "ID": "8",
    "_stage": "E2",
    "TOTAL_OMISIONES": 563,
    "OK": 563,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "9",
    "_stage": "E2",
    "TOTAL_OMISIONES": 440,
    "OK": 360,
    "FALTA: INICIAL": 12,
    "FALTA: CAJA + FINAL": 5,
    "CARPETA VACÍA": 9,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 10,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 5,
    "FALTA: INICIAL + CAJA": 37,
    "FALTA: INICIAL + FINAL": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "10",
    "_stage": "E2",
    "TOTAL_OMISIONES": 309,
    "OK": 309,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "11",
    "_stage": "E2",
    "TOTAL_OMISIONES": 689,
    "OK": 689,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "12",
    "_stage": "E2",
    "TOTAL_OMISIONES": 327,
    "OK": 327,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TAYCAR",
    "ID": "14",
    "_stage": "E2",
    "TOTAL_OMISIONES": 466,
    "OK": 451,
    "FALTA: INICIAL": 5,
    "FALTA: CAJA + FINAL": 3,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 4,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "15",
    "_stage": "E2",
    "TOTAL_OMISIONES": 284,
    "OK": 284,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AREVIR",
    "ID": "16",
    "_stage": "E2",
    "TOTAL_OMISIONES": 21,
    "OK": 21,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "17",
    "_stage": "E2",
    "TOTAL_OMISIONES": 241,
    "OK": 241,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "18",
    "_stage": "E2",
    "TOTAL_OMISIONES": 114,
    "OK": 114,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "19",
    "_stage": "E2",
    "TOTAL_OMISIONES": 481,
    "OK": 304,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 161,
    "CARPETA VACÍA": 10,
    "SIN CARPETA": 2,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 3,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GISOL",
    "ID": "20",
    "_stage": "E2",
    "TOTAL_OMISIONES": 376,
    "OK": 369,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 4,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 2,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLAN",
    "ID": "21",
    "_stage": "E2",
    "TOTAL_OMISIONES": 955,
    "OK": 947,
    "FALTA: INICIAL": 3,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 4,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "22",
    "_stage": "E2",
    "TOTAL_OMISIONES": 337,
    "OK": 230,
    "FALTA: INICIAL": 36,
    "FALTA: CAJA + FINAL": 7,
    "CARPETA VACÍA": 3,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 17,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 27,
    "FALTA: INICIAL + CAJA": 13,
    "FALTA: INICIAL + FINAL": 4
  },
  {
    "EMPRESA_RAIZ_MASTER": "GABETH",
    "ID": "23",
    "_stage": "E2",
    "TOTAL_OMISIONES": 471,
    "OK": 460,
    "FALTA: INICIAL": 5,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 5,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ESCARPIO",
    "ID": "24",
    "_stage": "E2",
    "TOTAL_OMISIONES": 337,
    "OK": 337,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TIERRAZOL",
    "ID": "25",
    "_stage": "E2",
    "TOTAL_OMISIONES": 149,
    "OK": 126,
    "FALTA: INICIAL": 3,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 16,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PROYEP",
    "ID": "52",
    "_stage": "E2",
    "TOTAL_OMISIONES": 332,
    "OK": 332,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "53",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1184,
    "OK": 1121,
    "FALTA: INICIAL": 2,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 22,
    "SIN CARPETA": 16,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 22,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "54",
    "_stage": "E2",
    "TOTAL_OMISIONES": 952,
    "OK": 887,
    "FALTA: INICIAL": 44,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 4,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 7,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 4,
    "FALTA: INICIAL + CAJA": 4,
    "FALTA: INICIAL + FINAL": 2
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "55",
    "_stage": "E2",
    "TOTAL_OMISIONES": 231,
    "OK": 209,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 8,
    "FALTA: CAJA": 13,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "56",
    "_stage": "E2",
    "TOTAL_OMISIONES": 192,
    "OK": 141,
    "FALTA: INICIAL": 32,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 2,
    "FALTA: CAJA": 6,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 10,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "57",
    "_stage": "E2",
    "TOTAL_OMISIONES": 344,
    "OK": 128,
    "FALTA: INICIAL": 2,
    "FALTA: CAJA + FINAL": 14,
    "CARPETA VACÍA": 13,
    "SIN CARPETA": 174,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 5,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + FINAL": 5
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "58",
    "_stage": "E2",
    "TOTAL_OMISIONES": 535,
    "OK": 462,
    "FALTA: INICIAL": 18,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 35,
    "FALTA: CAJA": 16,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 3,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "59",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1794,
    "OK": 1715,
    "FALTA: INICIAL": 15,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 5,
    "FALTA: CAJA": 44,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 15,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "60",
    "_stage": "E2",
    "TOTAL_OMISIONES": 301,
    "OK": 301,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "61",
    "_stage": "E2",
    "TOTAL_OMISIONES": 713,
    "OK": 710,
    "FALTA: INICIAL": 3,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MCORP",
    "ID": "62",
    "_stage": "E2",
    "TOTAL_OMISIONES": 682,
    "OK": 682,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MCORP",
    "ID": "63",
    "_stage": "E2",
    "TOTAL_OMISIONES": 427,
    "OK": 422,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 4,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "MCORP",
    "ID": "64",
    "_stage": "E2",
    "TOTAL_OMISIONES": 356,
    "OK": 345,
    "FALTA: INICIAL": 9,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "65",
    "_stage": "E2",
    "TOTAL_OMISIONES": 202,
    "OK": 2,
    "FALTA: INICIAL": 2,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 149,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 48,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "66",
    "_stage": "E2",
    "TOTAL_OMISIONES": 175,
    "OK": 129,
    "FALTA: INICIAL": 10,
    "FALTA: CAJA + FINAL": 2,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 27,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 6,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "67",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1760,
    "OK": 852,
    "FALTA: INICIAL": 12,
    "FALTA: CAJA + FINAL": 1,
    "CARPETA VACÍA": 53,
    "SIN CARPETA": 816,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + FINAL": 1,
    "FALTA: FINAL": 17,
    "FALTA: INICIAL + CAJA": 5,
    "FALTA: INICIAL + FINAL": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "68",
    "_stage": "E2",
    "TOTAL_OMISIONES": 1530,
    "OK": 1142,
    "FALTA: INICIAL": 23,
    "FALTA: CAJA + FINAL": 113,
    "CARPETA VACÍA": 3,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 140,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 107,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "69",
    "_stage": "E2",
    "TOTAL_OMISIONES": 318,
    "OK": 318,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "70",
    "_stage": "E2",
    "TOTAL_OMISIONES": 778,
    "OK": 776,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "71",
    "_stage": "E2",
    "TOTAL_OMISIONES": 674,
    "OK": 668,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "72",
    "_stage": "E2",
    "TOTAL_OMISIONES": 321,
    "OK": 11,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 3,
    "CARPETA VACÍA": 289,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 10,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 3,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + FINAL": 3
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLAN",
    "ID": "73",
    "_stage": "E2",
    "TOTAL_OMISIONES": 177,
    "OK": 176,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "74",
    "_stage": "E2",
    "TOTAL_OMISIONES": 800,
    "OK": 792,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 5,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PROYEP",
    "ID": "75",
    "_stage": "E2",
    "TOTAL_OMISIONES": 187,
    "OK": 187,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TIERRAZOL",
    "ID": "76",
    "_stage": "E2",
    "TOTAL_OMISIONES": 198,
    "OK": 112,
    "FALTA: INICIAL": 14,
    "FALTA: CAJA + FINAL": 9,
    "CARPETA VACÍA": 3,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 30,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 18,
    "FALTA: INICIAL + CAJA": 4,
    "FALTA: INICIAL + FINAL": 8
  },
  {
    "EMPRESA_RAIZ_MASTER": "REDNI",
    "ID": "77",
    "_stage": "E2",
    "TOTAL_OMISIONES": 291,
    "OK": 290,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "78",
    "_stage": "E2",
    "TOTAL_OMISIONES": 130,
    "OK": 49,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + FINAL": 8,
    "CARPETA VACÍA": 47,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 9,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 17,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "79",
    "_stage": "E2",
    "TOTAL_OMISIONES": 267,
    "OK": 189,
    "FALTA: INICIAL": 40,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 30,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 0,
    "FALTA: INICIAL + CAJA": 8,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "80",
    "_stage": "E2",
    "TOTAL_OMISIONES": 277,
    "OK": 165,
    "FALTA: INICIAL": 18,
    "FALTA: CAJA + FINAL": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 2,
    "FALTA: CAJA": 24,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 1,
    "FALTA: INICIAL + CAJA": 67,
    "FALTA: INICIAL + FINAL": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "81",
    "_stage": "E2",
    "TOTAL_OMISIONES": 852,
    "OK": 590,
    "FALTA: INICIAL": 32,
    "FALTA: CAJA + FINAL": 14,
    "CARPETA VACÍA": 163,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 18,
    "FALTA: INICIAL + CAJA + FINAL": 0,
    "FALTA: FINAL": 21,
    "FALTA: INICIAL + CAJA": 11,
    "FALTA: INICIAL + FINAL": 2
  }
];
export const FILTERS_MAP = {
  "ALSAFI": [
    "61",
    "10"
  ],
  "AREVIR": [
    "16"
  ],
  "AZTLAN": [
    "21",
    "73"
  ],
  "COPAD": [
    "COPAD"
  ],
  "COPI": [
    "9",
    "108",
    "67"
  ],
  "DAREGA": [
    "17",
    "59"
  ],
  "ESCARPIO": [
    "24"
  ],
  "FENA": [
    "23",
    "20",
    "53",
    "19",
    "54",
    "68",
    "18",
    "66",
    "69",
    "72",
    "78"
  ],
  "GABETH": [
    "68",
    "23"
  ],
  "GISOL": [
    "68",
    "20"
  ],
  "GZALEZ": [
    "68",
    "58",
    "18",
    "19",
    "53"
  ],
  "JDJ": [
    "66",
    "19",
    "58"
  ],
  "PERBOR": [
    "12",
    "55",
    "56"
  ],
  "REDNI": [
    "8",
    "77"
  ],
  "ROCADURA": [
    "7",
    "57",
    "81"
  ],
  "SAQEB": [
    "54",
    "71",
    "68"
  ],
  "SHAYE": [
    "65",
    "70"
  ],
  "TAYCAR": [
    "14"
  ],
  "TIERRAZOL": [
    "25",
    "76"
  ],
  "TOVAR": [
    "11",
    "74"
  ],
  "ULTRAPARK": [
    "22",
    "79",
    "80"
  ],
  "VIGOR": [
    "15",
    "60"
  ],
  "PROYEP": [
    "52",
    "75"
  ],
  "MCORP": [
    "62",
    "63",
    "64"
  ]
};
