// Archivo Auto-generado por Kinger
export const ERROR_TYPES = [
  "OK",
  "FALTA: INICIAL",
  "FALTA: CAJA + TERMINADO",
  "CARPETA VACÍA",
  "SIN CARPETA",
  "FALTA: CAJA",
  "FALTA: INICIAL + CAJA + TERMINADO",
  "FALTA: TERMINADO",
  "FALTA: INICIAL + CAJA",
  "FALTA: INICIAL + TERMINADO"
];
export const GLOBAL_TOTALS = {
  "FALTA: INICIAL": 99,
  "OK": 12239,
  "FALTA: CAJA + TERMINADO": 630,
  "CARPETA VACÍA": 417,
  "SIN CARPETA": 287,
  "FALTA: CAJA": 36,
  "FALTA: INICIAL + CAJA + TERMINADO": 40,
  "FALTA: TERMINADO": 60,
  "FALTA: INICIAL + CAJA": 9,
  "FALTA: INICIAL + TERMINADO": 2
};
export const RESUMEN_DATA = [
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "61",
    "_stage": "E1",
    "TOTAL_OMISIONES": 222,
    "OK": 214,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + TERMINADO": 6,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ALSAFI",
    "ID": "10",
    "_stage": "E1",
    "TOTAL_OMISIONES": 21,
    "OK": 21,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AREVIR",
    "ID": "16",
    "_stage": "E1",
    "TOTAL_OMISIONES": 34,
    "OK": 10,
    "FALTA: INICIAL": 4,
    "FALTA: CAJA + TERMINADO": 19,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "AZTLAN",
    "ID": "21",
    "_stage": "E1",
    "TOTAL_OMISIONES": 496,
    "OK": 467,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 28,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPAD",
    "ID": "COPAD",
    "_stage": "E1",
    "TOTAL_OMISIONES": 989,
    "OK": 919,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + TERMINADO": 28,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + TERMINADO": 40,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "9",
    "_stage": "E1",
    "TOTAL_OMISIONES": 526,
    "OK": 508,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 12,
    "CARPETA VACÍA": 5,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "COPI",
    "ID": "108",
    "_stage": "E1",
    "TOTAL_OMISIONES": 226,
    "OK": 198,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 5,
    "CARPETA VACÍA": 23,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "17",
    "_stage": "E1",
    "TOTAL_OMISIONES": 121,
    "OK": 41,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 79,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "DAREGA",
    "ID": "59",
    "_stage": "E1",
    "TOTAL_OMISIONES": 66,
    "OK": 34,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 5,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 27,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ESCARPIO",
    "ID": "24",
    "_stage": "E1",
    "TOTAL_OMISIONES": 665,
    "OK": 538,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 116,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 5,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 2,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + TERMINADO": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "23",
    "_stage": "E1",
    "TOTAL_OMISIONES": 330,
    "OK": 324,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 4,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "20",
    "_stage": "E1",
    "TOTAL_OMISIONES": 100,
    "OK": 98,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "53",
    "_stage": "E1",
    "TOTAL_OMISIONES": 125,
    "OK": 84,
    "FALTA: INICIAL": 5,
    "FALTA: CAJA + TERMINADO": 15,
    "CARPETA VACÍA": 15,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 3,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 9,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 9,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "54",
    "_stage": "E1",
    "TOTAL_OMISIONES": 15,
    "OK": 1,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 2,
    "CARPETA VACÍA": 2,
    "SIN CARPETA": 10,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "FENA",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 15,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 6,
    "CARPETA VACÍA": 8,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GABETH",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 330,
    "OK": 292,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 36,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GISOL",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 100,
    "OK": 87,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 12,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 624,
    "OK": 618,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 4,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 1,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "58",
    "_stage": "E1",
    "TOTAL_OMISIONES": 136,
    "OK": 135,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "18",
    "_stage": "E1",
    "TOTAL_OMISIONES": 226,
    "OK": 226,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 237,
    "OK": 225,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 10,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "GZALEZ",
    "ID": "53",
    "_stage": "E1",
    "TOTAL_OMISIONES": 5,
    "OK": 2,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 2,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "66",
    "_stage": "E1",
    "TOTAL_OMISIONES": 93,
    "OK": 36,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 57,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "JDJ",
    "ID": "19",
    "_stage": "E1",
    "TOTAL_OMISIONES": 43,
    "OK": 9,
    "FALTA: INICIAL": 33,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "PERBOR",
    "ID": "12",
    "_stage": "E1",
    "TOTAL_OMISIONES": 1279,
    "OK": 1138,
    "FALTA: INICIAL": 40,
    "FALTA: CAJA + TERMINADO": 49,
    "CARPETA VACÍA": 44,
    "SIN CARPETA": 1,
    "FALTA: CAJA": 3,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 3,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "REDNI",
    "ID": "8",
    "_stage": "E1",
    "TOTAL_OMISIONES": 263,
    "OK": 248,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 7,
    "SIN CARPETA": 6,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "7",
    "_stage": "E1",
    "TOTAL_OMISIONES": 1215,
    "OK": 1131,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 74,
    "CARPETA VACÍA": 5,
    "SIN CARPETA": 4,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 1,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "57",
    "_stage": "E1",
    "TOTAL_OMISIONES": 300,
    "OK": 296,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 3,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ROCADURA",
    "ID": "81",
    "_stage": "E1",
    "TOTAL_OMISIONES": 2091,
    "OK": 1844,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 242,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 1,
    "FALTA: INICIAL + CAJA": 2,
    "FALTA: INICIAL + TERMINADO": 1
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "54",
    "_stage": "E1",
    "TOTAL_OMISIONES": 459,
    "OK": 447,
    "FALTA: INICIAL": 1,
    "FALTA: CAJA + TERMINADO": 9,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 2,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "71",
    "_stage": "E1",
    "TOTAL_OMISIONES": 50,
    "OK": 44,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 4,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 1,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SAQEB",
    "ID": "68",
    "_stage": "E1",
    "TOTAL_OMISIONES": 2,
    "OK": 0,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 2,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "65",
    "_stage": "E1",
    "TOTAL_OMISIONES": 51,
    "OK": 51,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "SHAYE",
    "ID": "70",
    "_stage": "E1",
    "TOTAL_OMISIONES": 60,
    "OK": 54,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 5,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TAYCAR",
    "ID": "14",
    "_stage": "E1",
    "TOTAL_OMISIONES": 192,
    "OK": 76,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 0,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 116,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TIERRAZOL",
    "ID": "25",
    "_stage": "E1",
    "TOTAL_OMISIONES": 171,
    "OK": 164,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 6,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "11",
    "_stage": "E1",
    "TOTAL_OMISIONES": 964,
    "OK": 901,
    "FALTA: INICIAL": 8,
    "FALTA: CAJA + TERMINADO": 11,
    "CARPETA VACÍA": 11,
    "SIN CARPETA": 8,
    "FALTA: CAJA": 12,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 12,
    "FALTA: INICIAL + CAJA": 1,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "TOVAR",
    "ID": "74",
    "_stage": "E1",
    "TOTAL_OMISIONES": 275,
    "OK": 103,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 119,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 6,
    "FALTA: CAJA": 11,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 36,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "ULTRAPARK",
    "ID": "22",
    "_stage": "E1",
    "TOTAL_OMISIONES": 200,
    "OK": 183,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 15,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 2,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "15",
    "_stage": "E1",
    "TOTAL_OMISIONES": 288,
    "OK": 287,
    "FALTA: INICIAL": 0,
    "FALTA: CAJA + TERMINADO": 1,
    "CARPETA VACÍA": 0,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  },
  {
    "EMPRESA_RAIZ_MASTER": "VIGOR",
    "ID": "60",
    "_stage": "E1",
    "TOTAL_OMISIONES": 205,
    "OK": 185,
    "FALTA: INICIAL": 4,
    "FALTA: CAJA + TERMINADO": 15,
    "CARPETA VACÍA": 1,
    "SIN CARPETA": 0,
    "FALTA: CAJA": 0,
    "FALTA: INICIAL + CAJA + TERMINADO": 0,
    "FALTA: TERMINADO": 0,
    "FALTA: INICIAL + CAJA": 0,
    "FALTA: INICIAL + TERMINADO": 0
  }
];
export const FILTERS_MAP = {
  "ALSAFI": [
    "61",
    "10"
  ],
  "AREVIR": [
    "16"
  ],
  "AZTLAN": [
    "21"
  ],
  "COPAD": [
    "COPAD"
  ],
  "COPI": [
    "9",
    "108"
  ],
  "DAREGA": [
    "17",
    "59"
  ],
  "ESCARPIO": [
    "24"
  ],
  "FENA": [
    "23",
    "20",
    "53",
    "19",
    "54",
    "68"
  ],
  "GABETH": [
    "68"
  ],
  "GISOL": [
    "68"
  ],
  "GZALEZ": [
    "68",
    "58",
    "18",
    "19",
    "53"
  ],
  "JDJ": [
    "66",
    "19"
  ],
  "PERBOR": [
    "12"
  ],
  "REDNI": [
    "8"
  ],
  "ROCADURA": [
    "7",
    "57",
    "81"
  ],
  "SAQEB": [
    "54",
    "71",
    "68"
  ],
  "SHAYE": [
    "65",
    "70"
  ],
  "TAYCAR": [
    "14"
  ],
  "TIERRAZOL": [
    "25"
  ],
  "TOVAR": [
    "11",
    "74"
  ],
  "ULTRAPARK": [
    "22"
  ],
  "VIGOR": [
    "15",
    "60"
  ]
};
